services:
  # Satisfactory server
  satisfactory_server:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory_server
    profiles:
      - satisfactory_server
    restart: on-failure:5
    depends_on:
      main_satisfactory:
        condition: service_completed_successfully
    ports:
      - 7777:7777/udp
      - 7777:7777/tcp
    volumes:
      - satisfactory_server_config:/config
      - satisfactory_server_backups:/config/backups
      - satisfactory_server_gamefiles:/config/gamefiles
      - satisfactory_server_logs:/config/logs
      - satisfactory_server_saved:/config/saved
    networks:
      - satisfactory_network
    env_file:
      - ./satisfactory/env/satisfactory.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G

  satisfactory_backup:
    image: mazzolino/restic:latest
    container_name: satisfactory_backup
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - UID=${PUID:-1000}
      - GID=${PGID:-1000}
    profiles:
      - satisfactory_backup
#    depends_on:
#      - satisfactory_server
    restart: on-failure:5
    env_file:
      - ./satisfactory/env/satisfactory_backup.env
    volumes:
      - satisfactory_backup:/mnt/restic
      - satisfactory_server_saved:/data:ro
      - satisfactory_backup_cache:/.cache
    networks:
      - satisfactory_network
    security_opt:
      - no-new-privileges:true

volumes:
  satisfactory_backup:
    name: satisfactory_backup
  satisfactory_backup_cache:
    name: satisfactory_backup_cache
  satisfactory_server_config:
    name: satisfactory_server_config
  satisfactory_server_backups:
    name: satisfactory_server_backups
  satisfactory_server_gamefiles:
    name: satisfactory_server_gamefiles
  satisfactory_server_logs:
    name: satisfactory_server_logs
  satisfactory_server_saved:
    name: satisfactory_server_saved
