version: '3'
services:
    game:
        image: wolveix/satisfactory-server:latest
        profiles:
        - server
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - backups:/config/backups
            - saves:/config/saves
            - gamefiles:/config/gamefiles
            - extra:/config/extra
        environment:
            - MAXPLAYERS=8
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: on-failure:3

volumes:
    extra: {}
    saves: {}
    gamefiles: {}
    backups: {}
