version: "3.1"
services:
    satisfactory-server:
        image: wolveix/satisfactory-server:latest
        profiles:
            - satisfactory-server
        ports:
            - 7777:7777/udp
            - 15000:15000/udp
            - 15777:15777/udp
        volumes:
            - backups:/config/backups:rw
            - saves:/config/saves:rw
            - gamefiles:/config/gamefiles:rw
            - extra:/config/extra:rw
        env_file:
        - satisfactory.env
        restart: on-failure:3
    backup:
        image: offen/docker-volume-backup:latest
        profiles:
            - backup
        depends_on:
            - satisfactory-server        
        env_file:
        - backup.env
        volumes:
            - saves:/backup/my-app-backup:ro
            - archive:/archive:rw

volumes:
    extra: {}
    saves: {}
    gamefiles: {}
    backups: {} # Backup when server start
    archive: {} # Backup every 2 hours
