services:
  main_satisfactory:
    container_name: main_satisfactory
    image: alpine:latest
    profiles:
      - main_satisfactory
    volumes:
      - satisfactory_server_chown:/satisfactory_server:rw
      - satisfactory_openssh_config:/satisfactory_server/openssh_config:rw
      - satisfactory_backup:/satisfactory_server/backup:rw
      - satisfactory_backup_cache:/satisfactory_server/backup_cache:rw
      - satisfactory_server_config:/satisfactory_server/data:rw
      - satisfactory_server_backups:/satisfactory_server/backups:rw
      - satisfactory_server_gamefiles:/satisfactory_server/gamefiles:rw
      - satisfactory_server_logs:/satisfactory_server/logs:rw
      - satisfactory_server_saved:/satisfactory_server/saved:rw
    networks:
      - satisfactory_network
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
    # Fix root permissions on mounted volumes
    command: chown -R ${PUID:-1000}:${PGID:-1000} /satisfactory_server

volumes:
  satisfactory_server_chown:
    name: satisfactory_server_chown
  satisfactory_openssh_config:
    name: satisfactory_openssh_config
  satisfactory_backup:
    name: satisfactory_backup
  satisfactory_backup_cache:
    name: satisfactory_backup_cache
  satisfactory_server_config:
    name: satisfactory_server_config
  satisfactory_server_backups:
    name: satisfactory_server_backups
  satisfactory_server_gamefiles:
    name: satisfactory_server_gamefiles
  satisfactory_server_logs:
    name: satisfactory_server_logs
  satisfactory_server_saved:
    name: satisfactory_server_saved

networks:
  satisfactory_network:
    driver: bridge
    name: satisfactory_network