services:
  main_satisfactory:
    container_name: main_satisfactory
    image: alpine:latest
    profiles:
      - main_satisfactory
    volumes:
      - satisfactory_server_chown:/satisfactory_server:rw
      - satisfactory_openssh_config:/satisfactory_server/openssh_config:rw
      - satisfactory_backup:/satisfactory_server/backup:rw
      - satisfactory_backup_cache:/satisfactory_server/backup_cache:rw
      - satisfactory_data:/satisfactory_server/data:rw
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
    # Fix root permissions on mounted volumes
    command: chown -R ${PUID:-1000}:${PGID:-1000} /satisfactory_server

volumes:
  satisfactory_server_chown:
    name: satisfactory_server_chown
  satisfactory_openssh_config:
    name: satisfactory_openssh_config
  satisfactory_backup:
    name: satisfactory_backup
  satisfactory_backup_cache:
    name: satisfactory_backup_cache
  satisfactory_data:
    name: satisfactory_data

networks:
  satisfactory_network:
    driver: bridge
    name: satisfactory_network