services:
  satisfactory_backup:
    image: mazzolino/restic:latest
    container_name: satisfactory_backup
    profiles:
      - satisfactory_backup
    depends_on:
      - satisfactory_server
    restart: on-failure:5
    env_file:
      - ./env/satisfactory_backup.env
    volumes:
      - satisfactory_backup:/mnt/restic
      - satisfactory_server_file:/data:ro
    security_opt:
      - no-new-privileges:true
    network_mode: none
    cap_drop:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN

volumes:
  satisfactory_backup:
    name: satisfactory_backup
  satisfactory_server_config_lgsm:
    name: satisfactory_server_config_lgsm
  satisfactory_server_file:
    name: satisfactory_server_file
  satisfactory_server_log:
    name: satisfactory_server_log
